# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'yuwei-wu'

# google analytics
google-ID: 'UA-160796698-1'



menu:
  - name: About
    link: /about
  - name: Blogs
    link: /blogs
  - name: Tags
    link: /tags
  - name: Gallery
    link: /gallery
  - name: Contact Me
    link: /contact
  - name: Featured Projects
    submenu:
      - name: RoboCup
        link: /projects/RoboCup
      - name: Dance Robot
        link: /projects/DanceRobot
