# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'yuwei-wu'

# google analytics
google-ID: 'UA-160796698-1'



menu:
  - name: About
    link: /about
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
